schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

steps:
- script: |
    set -e
    docker-compose -f .devcontainer/docker-compose.test.yml build --no-cache --pull
    docker-compose -f .devcontainer/docker-compose.test.yml run vscode-azurecli-test
  displayName: Run Tests
