azure:
  AZURE_CLIENT_ID: 'your_azure_client_id'
  AZURE_SECRET: 'your_azure_secret'
  AZURE_SUBSCRIPTION_ID: 'your_azure_subscription_id'
  AZURE_TENANT: 'your_azure_tenant_id'
aws:
  AWS_ACCESS_KEY_ID: 'your_aws_access_key_id'
  AWS_SECRET_ACCESS_KEY: 'your_aws_access_key'
gce:
  GCE_EMAIL: 'your_gce_email'
  GCE_PROJECT: 'your_gce_project'
  GCE_CREDENTIALS_FILE_PATH: 'your_gce_credentials_file_path'
rax:
  RAX_CREDS_FILE: 'your_rax_credentials_file_path'
cloudstack:
  CLOUDSTACK_DOMAIN: 'your_cloudstack_domain'
  CLOUDSTACK_ACCOUNT: 'your_cloudstack_account'
  CLOUDSTACK_PROJECT: 'your_cloudstack_project'
  CLOUDSTACK_VPC: 'your_cloudstack_vpc'
  CLOUDSTACK_ZONE: 'your_cloudstack_zone'